line-length = 120
select = ["ALL"]
ignore = ["ANN101", "D107", "FBT003", "N802", "N803", "N806", "PLR2004", "SIM108"]

[per-file-ignores]
"__init__.py" = ["F401"]
"mainwindow.py" = ["E402"]

[flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
