line-length = 120

[lint]
select = ["ALL"]
ignore = [
  "ANN", "BLE001", "C90", "D1", "D211", "D213", "FBT", "N802", "N803", "N806", "PLR09", "PTH", "S60", "SIM105", "TRY300"
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"check_proxy.py" = ["PLW1510"]
"data_base.py" = ["ALL"]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"

[format]
quote-style = "single"
